#ifndef __GCALLBACK__
#define __GCALLBACK__
#include <functional>

#define GCALLBACK_0(FUNC, INS) std::bind(&FUNC, INS)
#define GCALLBACK_1(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1)
#define GCALLBACK_2(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2)
#define GCALLBACK_3(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3)
#define GCALLBACK_4(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4)
#define GCALLBACK_5(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5)
#define GCALLBACK_6(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6)
#define GCALLBACK_7(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7)
#define GCALLBACK_8(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8)
#define GCALLBACK_9(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9)
#define GCALLBACK_10(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10)
#define GCALLBACK_11(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11)
#define GCALLBACK_12(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12)
#define GCALLBACK_13(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13)
#define GCALLBACK_14(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14)
#define GCALLBACK_15(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15)
#define GCALLBACK_16(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15, std::placeholders::_16)
#define GCALLBACK_17(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15, std::placeholders::_16, std::placeholders::_17)
#define GCALLBACK_18(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15, std::placeholders::_16, std::placeholders::_17, std::placeholders::_18)
#define GCALLBACK_19(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15, std::placeholders::_16, std::placeholders::_17, std::placeholders::_18, std::placeholders::_19)
#define GCALLBACK_20(FUNC, INS) std::bind(&FUNC, INS, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8, std::placeholders::_9, std::placeholders::_10, std::placeholders::_11, std::placeholders::_12, std::placeholders::_13, std::placeholders::_14, std::placeholders::_15, std::placeholders::_16, std::placeholders::_17, std::placeholders::_18, std::placeholders::_19, std::placeholders::_20)


#endif